### ISSUE TITLE
Can't show more than 30 builds.

### ISSUE THREAD

**Issue by putsi** [tc-radiate/tc-radiate#6]
If I change the build count to more than 30, no builds are shown and no error is shown on the developer console.

**Comment by putsi** [comment]
If you have any idea where the problem is, please tell and I'll look into fixing it.

**Comment by mrbalihai** [comment]
I'm not sure, there's nothing in the code that would limit it (other than the team city API itself) as far as I can remember. I will investigate when I get the chance.

**Comment by putsi** [comment]
I'm running it with following settings:

```
Settings.buildsUrl = Settings.proxy + Settings.teamCityUrl + '/guestAuth/app/rest/builds?locator=project:ProjectName,running:any,branch:branched:any,count:30';

Settings.buildTypesUrl = Settings.proxy + Settings.teamCityUrl + '/guestAuth/app/rest/buildTypes?';

Settings.buildStatusUrl = Settings.proxy + Settings.teamCityUrl + '/guestAuth/app/rest/builds/branch:' + Settings.mainBranch + ',running:any,canceled:any?';
```

**Comment by zlamma** [comment]
Fix to this, and many other improvements are part of the 'most maintained' fork:  

https://github.com/zlamma/tc-radiate

**Comment by zlamma** [comment]
That fork has become the official version now, hence closing the issue.
