### ISSUE TITLE
Ability to show only one build per branch/project.

### ISSUE THREAD

**Issue by putsi** [tc-radiate/tc-radiate#7]
Current implementation shows multiple builds for branches and subprojects.
A simple ko.observablearray could be implemented to allow showing only the latest build per each branch and subproject.

**Comment by putsi** [comment]
I might create a pull request from this if I have time.

**Comment by zlamma** [comment]
This feature is the default in the 'most maintained' fork:   
https://github.com/zlamma/tc-radiate

It also contains [many other improvements](https://github.com/zlamma/tc-radiate#based-on-robbollonstc-radiate-with-improved-featuresfeatures).
